# Generated by Django 3.2.20 on 2023-08-03 12:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20230803_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='user-default_acghod', max_length=255, verbose_name='profile_image'),
        ),
    ]
