# Generated by Django 3.2.20 on 2023-08-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
