# Generated by Django 3.2.20 on 2023-08-13 09:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20230813_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='user-default_zft92h', max_length=255, verbose_name='profile_image'),
        ),
    ]
